pipeline {
   agent any

   stages {
      stage('pull code') {
         steps {
            checkout([$class: 'GitSCM', branches: [[name: '*/master']], doGenerateSubmoduleConfigurations: false, extensions: [[$class:'CheckoutOption',timeout:600],[$class:'CloneOption',depth:0,noTags:false,reference:'',shallow:false,timeout:600]], submoduleCfg: [], userRemoteConfigs: [[credentialsId: '231cdbe1-506f-479b-8dbd-a63b0eff86b5', url: 'git@github.com:wcongkevin/StockMarketCharting.git']]])
         }
      }
     stage('Build') {
           withMaven(
            maven: 'maven',
            mavenLocalRepo: '.repository') {
                sh "mvn clean install -Dmaven.test.skip=true"
        }
   }
   stage('deploy') {
    sshagent(credentials: ['deploy_ssh_key']) {
        sh 'ssh root@120.xx.95.105'
        sh 'docker run -d -p 8080:8080 -v /home/data:/webapps --name search tomcat:9.0'
        sh 'echo hello'
     }
   }
   }
}