spring:
  application:
    name: identity-service
  redis:
    host: localhost
    port: 6379

 
server:
  port: 5300
   
eureka:
  client:
    service-url:
      defaultZone: http://localhost:5000/eureka/
 
 
feign:
  hystrix:
    enabled: true
